baseURL = "https://weekly.oskarsh.ru/"
defaultContentLanguage = "ru"
title = "Еженедельные отчеты"
theme = ["hugo-video", "PaperMod"]
copyright = "© 2022 Шарипов Оскар (CC BY-SA 4.0)"

[params]
	defaultTheme = "auto"
	showReadingTime = true
	author = "Оскар"
	dateFormat = "2006-01-02"
	disableScrollToTop = true
	enableRobotsTXT = true

	[params.homeInfoParams]
	title = "Йоу, я Оскар 👋"
	content = """Мои [контакты][con]; наш [чат][cht]; ваш [rss][rss].

Текст распространяется под [CC BY-SA 4.0][cc].

[con]: https://oskarsh.ru/contact
[cht]: https://t.me/FlamingoSays
[rss]: https://weekly.oskarsh.ru/index.xml
[cc]: https://creativecommons.org/licenses/by-sa/4.0/deed.ru"""

[outputs]
	home = ["HTML", "RSS"]

[markup]
	[markup.goldmark.renderer]
		unsafe = true
