baseURL = "https://weekly.oskarsh.ru/"
defaultContentLanguage = "ru"
title = "Еженедельные отчеты"
theme = "PaperMod"
copyright = "© 2022 Шарипов Оскар (CC BY-SA 4.0)"

[params]
defaultTheme = "auto"
showReadingTime = true
author = "Оскар"
dateFormat = "2006-01-02"
disableScrollToTop = true
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS" ]
