baseURL = "https://weekly.oskarsh.ru/"
defaultContentLanguage = "ru"
title = "Еженедельные отчеты"
theme = ["hugo-video", "PaperMod"]
copyright = "© 2022 - 2023 Шарипов Оскар (CC BY-SA 4.0)"

[menu]
	[[menu.main]]
		identifier = "about"
		name = "Что происходит?"
		url = "/about/"
		weight = 1

	[[menu.main]]
		identifier = "flamingo"
		name = "фламинго 🦩"
		url = "/flamingo/"
		weight = 2

	[[menu.main]]
		identifier = "contact"
		name = "Связаться"
		url = "https://oskarsh.ru/contact"
		weight = 3

	[[menu.main]]
		identifier = "search"
		name = "Поиск"
		url = "/search/"
		weight = 4

[params]
	defaultTheme = "auto"
	showReadingTime = true
	author = "Оскар"
	dateFormat = "2006-01-02"
	disableScrollToTop = true
	disableFingerprinting = true
	enableRobotsTXT = true
	showPostNavLinks = true

	[params.assets]
	disableHLJS = true

	[params.fuseOpts]
	keys = ["title", "permalink", "summary", "content"]

	[params.homeInfoParams]
	title = "Йоу, я Оскар 👋"
	content = """Текст распространяется под [CC BY-SA 4.0][cc].

[cc]: https://creativecommons.org/licenses/by-sa/4.0/deed.ru"""

[outputs]
	home = ["HTML", "RSS", "JSON"]

[markup]
	[markup.goldmark.renderer]
		unsafe = true

	[markup.highlight]
		lineNos = true
		lineNumbersInTable = true
		tabWidth = 4
