baseURL = "https://weekly.oskarsh.ru/"
defaultContentLanguage = "ru"
title = "Еженедельные отчеты"
theme = "PaperMod"

[params]
defaultTheme = "auto"
showReadingTime = true
author = "Оскар"
dateFormat = "2006-01-01"
disableScrollToTop = true
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS" ]
