name: Build static site and deploy with ssh

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2
        with:
          submodules: true
          lfs: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@c03b5dbed22245418539b65eb9a3b1d5fdd9a0a6  # v2.5.0
        with:
          hugo-version: '0.97.3'

      - name: Build static site
        run: hugo

      - name: Deploy to server
        uses: up9cloud/action-rsync@d2ada8da628e85b41b9a43e4ac9acb3626e1d7cf
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SOURCE: public/
          TARGET: ${{ secrets.DEPLOY_TARGET }}
          VERBOSE: true
